### PR TITLE
Gym new step API update

### PR DESCRIPTION
**Pull request by MatteoH2O1999**
Hey @hsahovic,
I updated the openAI wrapper to use the new API. Right now it is disabled by default, I would wait for ML libraries to implement the changes before changing the default.

I also removed the default opponent in EnvPlayer as discussed in #306

Let me know what you think

### CODE REVIEW

**Comment by hsahovic** [comment]
Thanks @MatteoH2O1999 - I'll take a look at it and the gym changes

**Comment by MatteoH2O1999** [comment]
Added background methods for accepting and sending challenges with OpenAIGym as requested in #314

**Comment by hsahovic** [comment]
This is good overall - making all of the internals weakly private makes sense, the addition of `background_accept_challenge` is great and moving forward with the new API is nice. Thanks again for your amazing work @MatteoH2O1999 !

One question though - why get rid of the default for `opponent`?
Advanced users will look into how to customize the agent they use for training, while providing a default makes it simpler for new users to get started. I can be persuaded to remove the default, but I'm curious regarding your ideas on it.

**Comment by hsahovic** [comment]
I think this is a good solution yeah, removing `None` will make things clearer

**Review by hsahovic — APPROVED** [review]

**Comment by hsahovic** [comment]
Thanks @MatteoH2O1999 !

**Pull request merged**
