### PR TITLE
Interface rework with background thread and OpenAI gym env API

### PR DESCRIPTION
**Pull request by MatteoH2O1999**
New pull request for @hsahovic request for a rework on the general API

### CODE REVIEW

**Comment by MatteoH2O1999** [comment]
This should also work in jupyter notebooks

**Comment by MatteoH2O1999** [comment]
Sorry, marked this ready by mistake. Still need to write documentation and examples once the API get accepted. Let me know what you think

**Comment by MatteoH2O1999** [comment]
Added an example with keras-rl2 1.0.5 and tensorflow 2.5

**Comment by MatteoH2O1999** [comment]
Hey @hsahovic,
I think this is ready to be merged. I already wrote a new example and updated the tutorial with the new wrapper.

**Comment by hsahovic** [comment]
@MatteoH2O1999 thanks a lot - I'll take a bit of time to review it integrally and merge it

**Comment by hsahovic** [comment]
I went over a good chunk of it during the weekend - I'll merge it sometime this week.

**Review by hsahovic — APPROVED** [review]

**Comment by hsahovic** [comment]
Thanks @MatteoH2O1999 !

**Pull request merged**
