### PR TITLE
Force Switch Battle Property Tracking Bugfix

### PR DESCRIPTION
**Pull request by cameronangliss**
I found that force_switch is not being tracked correctly, as it should always be of type `bool`, but I have found that sometimes it returns `[True]`. Here is an example request message that shows why the error is happening:

```
2023-12-26 16:45:56,358 - ShowdownEnv 1 - ERROR - Unhandled exception raised while handling message:
>battle-gen4randombattle-80371
|request|{"forceSwitch":[true],"side":{"name":"ShowdownEnv 1","id":"p1","pokemon":[{"ident":"p1: Glaceon","details":"Glaceon, L88, M","condition":"0 fnt","active":true,"stats":{"atk":113,"def":244,"spa":278,"spd":217,"spe":165},"moves":["protect","wish","hiddenpowerground","icebeam"],"baseAbility":"snowcloak","item":"leftovers","pokeball":"pokeball"},{"ident":"p1: Hitmonchan","details":"Hitmonchan, L87, M","condition":"229/229","active":false,"stats":{"atk":232,"def":187,"spa":111,"spd":241,"spe":182},"moves":["rapidspin","stoneedge","icepunch","drainpunch"],"baseAbility":"ironfist","item":"leftovers","pokeball":"pokeball"},{"ident":"p1: Raikou","details":"Raikou, L76","condition":"262/262","active":false,"stats":{"atk":135,"def":157,"spa":219,"spd":196,"spe":219},"moves":["aurasphere","thunderbolt","hiddenpowerice","calmmind"],"baseAbility":"pressure","item":"lifeorb","pokeball":"pokeball"},{"ident":"p1: Gyarados","details":"Gyarados, L78, F","condition":"276/276","active":false,"stats":{"atk":240,"def":168,"spa":139,"spd":201,"spe":171},"moves":["dragondance","earthquake","substitute","waterfall"],"baseAbility":"intimidate","item":"leftovers","pokeball":"pokeball"},{"ident":"p1: Magmortar","details":"Magmortar, L83, M","condition":"129/260","active":false,"stats":{"atk":162,"def":159,"spa":255,"spd":205,"spe":185},"moves":["fireblast","thunderbolt","focusblast","substitute"],"baseAbility":"flamebody","item":"leftovers","pokeball":"pokeball"},{"ident":"p1: Meganium","details":"Meganium, L90, M","condition":"52/290","active":false,"stats":{"atk":152,"def":231,"spa":201,"spd":231,"spe":195},"moves":["energyball","aromatherapy","synthesis","leechseed"],"baseAbility":"overgrow","item":"leftovers","pokeball":"pokeball"}]},"noCancel":true,"rqid":20}
```

Notice that we have `"forceSwitch":[true]`. I fix this bug by indexing into the first element of the request JSON's `forceSwitch` attribute.

### CODE REVIEW

**Comment by hsahovic** [comment]
Good catch - thanks for the fix. Can you add a unit test checking that the message is parsed properly?

**Comment by hsahovic** [comment]
@cameronangliss let me know if you need a hand with this :)

**Comment by cameronangliss** [comment]
Hi @hsahovic, sorry, I saw what you wrote but I've just not gotten around to adding the unit tests yet. If you feel like you have the time and want to get this through quickly I'd have no issue with it :) If not though, I can't say for sure when I'll be able to look into that myself, as I'm getting rather busy as of late.

**Comment by hsahovic** [comment]
No problem - i'll take a look whenever I have some time for `poke-env` :)

**Comment by hsahovic** [comment]
I'm closing this for now - let me know if you want to reopen it!

**Comment by cameronangliss** [comment]
Hi Haris! I'm done with my semester now so I have time to finish this PR. Open it back up and I'll get this done.

**Comment by cameronangliss** [comment]
Update: I've got this branch working with updated unit tests up, so it should be good as soon as you reopen it.

**Review by hsahovic — APPROVED** [review]

**Comment by hsahovic** [comment]
Thanks @cameronangliss !

**Pull request merged**
