### PR TITLE
remove openai branding, update gym terminology with gymnasium

### PR DESCRIPTION
**Pull request by acxz**
follow up of #467 
address #453 

cc @cameronangliss 

no logic change whatsoever, just renaming.

### CODE REVIEW

**Comment by cameronangliss** [comment]
Good call @acxz, this looks good to me at a glance. There seems to be something wrong with the CI (not due to your changes, it seems to be in other PRs too) so we should wait until that is fixed first.

**Review by hsahovic — APPROVED** [review]

**Comment by hsahovic** [comment]
Thanks @acxz - this looks good

**Comment by hsahovic** [comment]
@acxz Unfortunately it looks like your PR conflicts which changes that I just merged - i didn't realized it was the case. Can you rebase and fix the conflict? 
I can also fork your branch and do it if you prefer.

**Comment by cameronangliss** [comment]
Hey! Sorry, but would it be alright if we went for "PokeEnv" instead of "GymnasiumEnv"? If you could get all the annoying renaming done here and save me the trouble in #663 (where I'm moving us away from gymnasium and into pettingzoo), that would be so amazing. I figure PettingZooEnv is a bit too long, so PokeEnv seems nice to me.

**Comment by acxz** [comment]
rebased

**Comment by hsahovic** [comment]
Amazing, thanks!

**Pull request merged**
