### PR TITLE
Exploring DummyPlayer usage

### PR DESCRIPTION
**Pull request by Benjamin-Etheredge**

### CODE REVIEW

**Comment by Benjamin-Etheredge** [comment]
Still trying to figure out the async stuff for sending and accepting challenges automatically.

**Comment by Benjamin-Etheredge** [comment]
Exploring #207

**Comment by Benjamin-Etheredge** [comment]
While I was able to get gym registering different environments so I could just call something like `gym.make("RandomSingles-v8")`, I could not get it to work in parallel. Something hangs during `reset()` when two environments are created. I'm working on an example case for replicating it. 

Getting the ability to run multiple environments in parallel is really needed for faster training through `VecEnvs` like in OpenAI Baselines.

I'm still debugging it, but I'm a super novice with the async paradigm.

**Comment by hsahovic** [comment]
@Benjamin-Etheredge to get multiple envs in parallel for training you'll get multiple instances of `PlayerEnv` as it is currently set-up to have one active battle at a time. That doesn't prevent having one shared model being trained though.

**Comment by Benjamin-Etheredge** [comment]
@hsahovic something is going on with multiple instances of `PlayerEnv`. For some reason, everything breaks if I instantiate 2 `PlayerEnv` objects. It creates all 4 players and starts games for 2 envs but hangs on `reset` calls.

I'm not sure if it's an issue with the underlying implementation with async stuff or just my extra code. I'm attempting to mimic your implementation of putting the algorithm logic on a separate thread and running the event loop on the main thread. No dice yet.

**Pull request closed without merging**
